title: CDE4301 Space Radiation Payload
description: An empty documentation page for the Space Radiation Monitoring and Experiment Payload for NUS CDE4301
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/favicon.ico"
